---
# creating a playbook to install mongodb in db server

# Where would you like to install it
- hosts: db

  # logs requires
  gather_facts: yes

  # allow admin access
  become: true

  # add the instructions tasks
  tasks:
    - name: installing mongodb in db server
      apt: pkg=mongodb state=present

    - name: Update bind_ip to 0.0.0.0
      lineinfile:
        path: ../../etc/mongodb.conf
        line: "bind_ip = 0.0.0.0"

    - name: open port in mongodb.conf
      lineinfile:
        path: ../../etc/mongodb.conf
        regexp: "^# port = 27017"
        line: "port = 27017"

    - name: restart mongodb service
      service: name=mongodb state=restarted
