apiVersion: v1
kind: Service

metadata:
  name: mongo-database-svc
  namespace: default
spec:
  ports:
    - nodePort: 30002
      port: 27017
      targetPort: 27017
  selector:
    app: mongo-database
  type: NodePort