apiVersion: apps/v1
kind: Deployment

metadata:
  name: sparta-app-deployment
spec:
  selector:
    matchLabels:
      app: sparta-app
  replicas: 3
  template:
    metadata:
      labels:
        app: sparta-app
    spec:
      containers:
        - name: sparta-app
          image: spencerley/spencer-sparta-test-app:latest
          ports:
            - containerPort: 3000