apiVersion: v1
kind: Service

metadata:
  name: sparta-app-svc
  namespace: default
spec:
  ports:
    - nodePort: 30003
      port: 3000
      targetPort: 3000
  selector:
    app: sparta-app
  type: NodePort
