# Starts with --- three dashes
---

# where do you want to run or install this playbook
- hosts: web

# would you like to see the logs?
  gather_facts: yes

# provide admin access to this playbook - use sudo
  become: true

# instructions - tasks install nginx in agent node
  tasks:
  - name: Configure/install nginx on the agent node
    apt: pkg=nginx state=present
