---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongo-database-deployment

spec:
  selector:
    matchLabels:
      app: mongo-database
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-database
    spec:
      containers:
        - name: mongo-database
          image: mongo:latest
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service

metadata:
  name: mongo-database-svc
  namespace: default
spec:
  ports:
    - nodePort: 30002
      port: 27017
      targetPort: 27017
  selector:
    app: mongo-database
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: sparta-app-deployment
spec:
  selector:
    matchLabels:
      app: sparta-app
  replicas: 3
  template:
    metadata:
      labels:
        app: sparta-app
    spec:
      containers:
        - name: sparta-app
          image: spencerley/spencer-sparta-test-app:latest
          env:
            - name: DB_HOST
              value: "mongodb://mongo-database-svc:27017/posts"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service

metadata:
  name: sparta-app-svc
  namespace: default
spec:
  ports:
    - nodePort: 30003
      port: 3000
      targetPort: 3000
  selector:
    app: sparta-app
  type: NodePort
